Set WshShell = WScript.CreateObject("WScript.Shell")

WScript.sleep 200
WshShell.Run "cmd"
WScript.sleep 40
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4
wshshell.sendkeys "{F11}"
WScript.sleep 4