Set WshShell = WScript.CreateObject("WScript.Shell")

WScript.sleep 200
WshShell.Run "cmd"
WScript.sleep 40
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"
wshshell.sendkeys "Y"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "o"
WScript.sleep 4
wshshell.sendkeys "m"
WScript.sleep 4
wshshell.sendkeys "p"
WScript.sleep 4
wshshell.sendkeys "u"
WScript.sleep 4
wshshell.sendkeys "t"
WScript.sleep 4
wshshell.sendkeys "e"
WScript.sleep 4
wshshell.sendkeys "r"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys " "
WScript.sleep 4
wshshell.sendkeys "s"
WScript.sleep 4
wshshell.sendkeys "i"
WScript.sleep 4
wshshell.sendkeys "c"
WScript.sleep 4
wshshell.sendkeys "k"
WScript.sleep 10
wshshell.sendkeys "{ENTER}"
WshShell.sendkeys "cls"
WScript.sleep 4
wshShell.sendkeys "{ENTER}"